import { ArrowLeft, ArrowRight } from 'lucide-react'
import { useEffect, useState } from 'react'
const slides=[
  ['https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1800&q=85','The Residence','Spaces in perfect balance'],
  ['https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1800&q=85','The Interiors','Materiality with a warm soul'],
  ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1800&q=85','The Garden','Nature at your doorstep'],
  ['https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?auto=format&fit=crop&w=1800&q=85','The Arrival','A warm welcome, every day'],
  ['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1800&q=85','The Kitchen','Crafted for gathering'],
  ['https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1800&q=85','The View','A horizon all your own'],
]
function Gallery(){const [active,setActive]=useState(0);useEffect(()=>{const t=setInterval(()=>setActive(v=>(v+1)%slides.length),5000);return()=>clearInterval(t)},[]);const move=d=>setActive(v=>(v+d+slides.length)%slides.length);return <section id="gallery" className="bg-slate-100 py-24 sm:py-32"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="mb-12 flex items-end justify-between"><div><p className="text-xs font-bold tracking-[.2em] text-amber-700">A CLOSER LOOK</p><h2 className="mt-3 font-serif text-5xl sm:text-6xl">Designed to be <em className="font-normal">felt.</em></h2></div><div className="flex gap-2"><button onClick={()=>move(-1)} className="rounded-full border p-3" aria-label="Previous image"><ArrowLeft/></button><button onClick={()=>move(1)} className="rounded-full border p-3" aria-label="Next image"><ArrowRight/></button></div></div><div className="overflow-hidden rounded-2xl"><div className={`gallery-track slide-${active} flex transition-transform duration-700`}>{slides.map(([image,label,detail])=><article key={label} className="relative min-w-full"><img className="h-[480px] w-full object-cover sm:h-[570px]" src={image} alt={label}/><div className="absolute inset-0 bg-gradient-to-t from-black/65"/><div className="absolute bottom-10 left-10 text-white"><p className="text-xs font-bold tracking-[.18em] text-amber-200">{label.toUpperCase()}</p><h3 className="mt-2 font-serif text-4xl">{detail}</h3></div></article>)}</div></div><div className="mt-6 flex gap-2">{slides.map((s,i)=><button key={s[1]} className={`h-1.5 rounded-full ${i===active?'w-10 bg-slate-900':'w-4 bg-slate-300'}`} onClick={()=>setActive(i)} aria-label={`View ${s[1]}`}/>)}</div></div></section>};export default Gallery
