import { LogOut, Menu, X } from 'lucide-react'
import { useState } from 'react'
import { useAuth } from '../auth/AuthContext'
const links = ['Overview', 'Gallery', 'Floor Plans', 'Calculator', 'Contact']
function Navbar({ onAuthOpen }) {
 const [open, setOpen] = useState(false); const close = () => setOpen(false); const { user, signOut } = useAuth()
 const accountControl = user ? <div className="flex items-center gap-3"><span className="hidden text-sm text-white/80 xl:block">Hi, {user.name}</span><button className="rounded-full bg-white/15 px-4 py-3 text-sm font-bold text-white hover:bg-white/25" type="button" onClick={signOut}><span className="hidden sm:inline">Sign out</span><LogOut className="sm:hidden" size={18}/></button></div> : <button className="rounded-full bg-amber-300 px-5 py-3 text-sm font-bold text-slate-900" type="button" onClick={onAuthOpen}>Sign in</button>
 return <header className="absolute inset-x-0 top-0 z-20"><nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-8" aria-label="Main navigation"><a className="font-serif text-3xl font-semibold text-white" href="#overview">AUREA<span className="text-amber-300">.</span></a><div className="hidden gap-8 lg:flex">{links.map(link => <a className="text-sm text-white/80 hover:text-white" key={link} href={`#${link.toLowerCase().replace(' ', '-')}`}>{link}</a>)}</div><div className="hidden lg:block">{accountControl}</div><button className="text-white lg:hidden" type="button" aria-label="Toggle navigation" aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></nav>{open && <div className="mx-5 rounded-2xl bg-white p-5 shadow-2xl lg:hidden"><div className="flex flex-col gap-4">{links.map(link => <a className="font-medium" key={link} href={`#${link.toLowerCase().replace(' ', '-')}`} onClick={close}>{link}</a>)}{user ? <button className="rounded-full bg-slate-900 px-5 py-3 text-center font-bold text-white" type="button" onClick={() => { signOut(); close() }}>Sign out</button> : <button className="rounded-full bg-slate-900 px-5 py-3 text-center font-bold text-white" type="button" onClick={() => { onAuthOpen(); close() }}>Sign in</button>}</div></div>}</header>
}
export default Navbar
