-- Run this migration in Supabase SQL Editor or with the Supabase CLI.
-- It creates the properties table and restricts management actions to admins.

create type public.app_role as enum ('admin', 'member');

create table public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role public.app_role not null default 'member',
  created_at timestamptz not null default now()
);

create table public.properties (
  id bigint generated by default as identity primary key,
  title text not null,
  price numeric not null check (price >= 0),
  area numeric not null check (area >= 0),
  bedrooms integer not null check (bedrooms >= 0),
  bathrooms integer not null check (bathrooms >= 0),
  type text not null,
  image_url text not null,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles
    where user_id = auth.uid() and role = 'admin'
  );
$$;

alter table public.user_roles enable row level security;
alter table public.properties enable row level security;

create policy "Users can view their own role" on public.user_roles for select to authenticated using ((select auth.uid()) = user_id);
create policy "Anyone can view properties" on public.properties for select to anon, authenticated using (true);
create policy "Admins can add properties" on public.properties for insert to authenticated with check ((select public.is_admin()));
create policy "Admins can update properties" on public.properties for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "Admins can delete properties" on public.properties for delete to authenticated using ((select public.is_admin()));

-- After creating the administrator in Authentication > Users, run this once.
-- Replace ADMIN_USER_UUID with that user's UUID:
-- insert into public.user_roles (user_id, role)
-- values ('ADMIN_USER_UUID', 'admin')
-- on conflict (user_id) do update set role = excluded.role;
